### PR TITLE
inspector_sink: update gui_hint logic to comply with 3.7.12.0

### LINKED ISSUE #20: QT GUI Inspector Sink template error
QT GUI Inspector Sink is not working with [GNURadio 3.7.12.0](https://github.com/gnuradio/gnuradio/releases/tag/v3.7.12.0).

```
Generating: '/home/karel/build/gr-inspector/examples/signal_detection.py'

Executing: /usr/bin/python2 -u /home/karel/build/gr-inspector/examples/signal_detection.py

  File "/home/karel/build/gr-inspector/examples/signal_detection.py", line 77
    self.inspector_qtgui_sink_vf_0 = Template error: #set $win = 'self._%s_win'%$id
                                                  ^
SyntaxError: invalid syntax

>>> Done (return code 1)
```

### PR DESCRIPTION
**Pull request by karel**
Fixes #20, according to https://github.com/gnuradio/gnuradio/commit/b5396df5547a5c29218a18a469454f5db03e6ab5.

### CODE REVIEW

**Comment by sbmueller** [comment]
@karel- thanks, however does this break support for all GR versions < 3.7.12?
@marcusmueller maybe you can help here as well?
Original PR: https://github.com/gnuradio/gnuradio/pull/1418
It seems as this was an API change. All core *.xml have been changed to the new format, but what about OOTs?

**Comment by karel** [comment]
@sbmueller yes, this breaks support for older versions. I am not aware of an easy fix to keep it backwards compatible.

**Comment by marcusmueller** [comment]
does https://github.com/gnuradio/gnuradio/commit/20ef863e86289107bc4c6cc375edd5890a363694 help here?

**Comment by marcusmueller** [comment]
Does not doing what @karel- does here and using head of maint-3.7 or master help?

**Comment by sbmueller** [comment]
@marcusmueller According to mails on the list, maint-3.7 does not help. For now I'm refraining from this PR because it will break support for all older GR versions. If there is no fix for GR 3.7.12 in sight, I will bite the bullet and raise gr-inspecor's dependency to GR 3.7.12.
Could you provide feedback on this?

**Comment by sbmueller** [comment]
Fixed since GNU Radio 3.7.13.3 (https://github.com/gnuradio/gnuradio/commit/dbdd204ccd3e4d174f4390bcd0948f33f1a8bf0d)

**Pull request closed without merging**
